version: "3.8"

networks:
  jenkins_slave:
    external: false

volumes:
  jenkins: null
  jenkins_slave: null
  docker_data: null
  ssh_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker/jenkins/.ssh
      o: bind

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_slave

  jenkins_slave:
    container_name: jenkins_slave
    restart: always
    build: 
      context: $PWD/docker/jenkins
      dockerfile: Dockerfile
    volumes:
      - docker_data:/var/lib/docker/btrfs
      - jenkins_slave:/home/jenkins
      - ssh_data:/home/jenkins/.ssh
    networks:
      - jenkins_slave
    cap_add:
      - NET_ADMIN
